name: Maven Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Should the maven release plugin do a dry run"
        type: boolean
        required: true
        default: true
      releaseVersion:
        description: "The release version for the artifact"
        required: true
        default: "A.B.C"
      developmentVersion:
        description: "The new development version for the artifact"
        required: true
        default: "A.B.C-SNAPSHOT"

jobs:
  build:
    uses: stacs/actions/.github/workflows/maven-release.yaml@v2
    secrets: inherit
    with:
      dryRun: ${{inputs.dryRun}}
      releaseVersion: ${{inputs.releaseVersion}}
      developmentVersion: ${{inputs.developmentVersion}}

